# Generated by Django 4.1.3 on 2022-11-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='done',
            field=models.CharField(max_length=10000),
        ),
    ]
