# Generated by Django 4.1.3 on 2022-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_alter_shoppingitem_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='done',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='beschreibung',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
