# Generated by Django 4.1.3 on 2022-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_remove_shoppingitem_done_shoppingitem_beschreibung'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
