# Generated by Django 4.1.3 on 2022-11-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_shoppingitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='beschreibung',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
