# Generated by Django 4.1.3 on 2022-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_alter_shoppingitem_beschreibung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='beschreibung',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
