# Generated by Django 4.1.3 on 2022-11-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_alter_shoppingitem_beschreibung'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingItem',
            new_name='Item',
        ),
    ]
