# Generated by Django 4.1.3 on 2022-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0007_rename_shoppingitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
