# Generated by Django 4.1.3 on 2022-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0008_item_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='UserID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='public',
            field=models.CharField(default='', max_length=200),
        ),
    ]
